sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
    - master
    - "/^v?[0-9\\.]+/"
cache:
  - composer
  - "$HOME/.composer/cache"
php:
  - 7.0
  - 7.2
env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=nightly WP_MULTISITE=0
before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - composer global require "phpunit/phpunit=4.8.*|6.*"
  - composer install
script:
  - phpunit
after_success:
  - sed -i -e "s/nightly/${TRAVIS_TAG}/" _anchors.php
  - curl https://raw.githubusercontent.com/miya0001/auto-build/master/auto-build.sh
    | bash
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "kSPKr+yZ6BqAvYW9Y9FUUyUVg6v37iiG7JJXAS44ypXTAuWGqXUJocbUTCb90DgegL3Cgww8CVoYzYHngiBsyB+jWKMBBFUQpk6k6iQXAk4WAG1+2987mhKyiKjIJEzoS4vgSIs/6ZTEet5TWNQZWGoWbR9uNDvtkbRFQFtcvlBsjuqtuExMXIG+hqUA/l6XWHXCOUbZmMVpd7m0e99f/dsVpOhiKmIYuzoowCuhQAhfYJVSkjwTJsuIUbbhysxwSV7mdo+7eTt3HHEzZ9xip4Enu5e7XZPrrwwb/R3y6pygb48gw86xfSyOYoqwIH28XnBv2anAjkTbW48z0ZRgTGywzq6XkDxtGn7r4lzk5ISwA68/QNytHOFsiYrkDaAMrB7KeD3M1+xcID2XPU3SpCeqrttMJrWUbd+54qnh+TS4v7KKXPehLo/uiqOsigokVyGIaqravibE2Iy0giVjoudW8HRsu6ETESwcHA/D0cLHrNu6Brw5D/SFzSWkJkR4aEfcQqIM+7OsnwptqUvgXWK4sK+KBe3MgPA/hmDGoBE/l7tn2rBjsHwW1USHfWAQWYWk9S2ZLjt0S/X+HNjw9Wk68YhlYUWPf+OWRtZs4oymjz2AP+xadbH5ymNG0KA38fQyqLcvg1TBazFL8Ed1erz4a15820nlJk/AlhVcOeY="
  file: _anchors.zip
  on:
    tags: true
    repo: miya0001/_anchors
